language: ruby

before_install:
  - gem install bundler -v '< 2'

dist: xenial

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-1.7.27
  - jruby-9.1
  - jruby-9.2

sudo: false

env:
  - PURE_RUBY=1
  - KITCHEN_SINK=1

script: >
  (echo "travis_fold:start:sdkbuild") &&
  (bundle exec rake build) &&
  (echo "travis_fold:end:sdkbuild") &&
  (bundle exec rake test:spec)

bundler_args: --without docs repl

matrix:
  exclude:
    - rvm: jruby-1.7.27
      env: KITCHEN_SINK=1
    - rvm: jruby-9.1
      env: KITCHEN_SINK=1
    - rvm: jruby-9.2
      env: KITCHEN_SINK=1
  include:
    - rvm: 2.3
      env: OLD_OJ=1
    - rvm: 2.3
      env: OLD_OX=1
    - rvm: 2.3
      env: NO_H2=1
  allow_failures:
    - rvm: jruby-1.7.27
    - rvm: jruby

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/4442efd380ec811746d9"
    on_success: change
    on_failure: always
    on_start: false
