language: ruby

before_install:
  - gem install bundler -v '< 2'

dist: trusty

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-1.7.27
  - jruby

sudo: false

env:
  - PURE_RUBY=1
  - KITCHEN_SINK=1

before_script: cat /home/travis/.rvm/log/*_jruby-1.7.27/gemsets.import.global.log /home/travis/.rvm/log/*_jruby-1.7.27/gemsets.import.default.log
 
script: rake build && rake test:spec

bundler_args: --without docs repl

matrix:
  exclude:
    - rvm: jruby-1.7.27
      env: KITCHEN_SINK=1
    - rvm: jruby
      env: KITCHEN_SINK=1
  include:
    - rvm: 2.3
      env: OLD_OJ=1
    - rvm: 2.3
      env: OLD_OX=1
    - rvm: 2.3
      env: NO_H2=1
  allow_failures:
    - rvm: jruby-1.7.27
    - rvm: jruby

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/4442efd380ec811746d9"
    on_success: change
    on_failure: always
    on_start: false
