rvm:
  - 1.8.7
  - 1.9.3
  - 1.9.2
  - 2.0.0
#  - jruby      # Running out of memory on Travis
#  - ruby-head  # RedCloth does not compile on head
#  - 1.8.6      # unsupported

script: "bundle exec rake"
env: "CI=1 SUITE=1 "
bundler_args: "--without repl documentation"

branches:
  only:
    - master
